import { BaseModel, manyToMany, pk, table } from "@decaf-ts/core";
import { model, Model, ModelArg, required } from "@decaf-ts/decorator-validation";
import {
  clearSchemaCache,
  createIndexSQL,
  createTableSQL,
  generateDDL,
  translateModel,
} from "../../src";
import { TestModel } from "../TestModel";

Model.setBuilder(Model.fromModel);

@table("gen_tag")
@model()
class GenTag extends BaseModel {
  @pk({ type: Number })
  id!: number;

  @required()
  label!: string;

  constructor(arg?: ModelArg<GenTag>) {
    super(arg);
  }
}

@table("gen_post")
@model()
class GenPost extends BaseModel {
  @pk({ type: Number })
  id!: number;

  @required()
  title!: string;

  @manyToMany(GenTag, undefined, true)
  tags!: GenTag[];

  constructor(arg?: ModelArg<GenPost>) {
    super(arg);
  }
}

describe("DDL generation", () => {
  beforeEach(() => clearSchemaCache());

  it("emits sqlite CREATE TABLE with dialect quoting and pk", () => {
    const schema = translateModel(TestModel, "sqlite");
    const sql = createTableSQL(schema);
    expect(sql).toContain('CREATE TABLE IF NOT EXISTS "tst_user"');
    expect(sql).toContain('"id" INTEGER PRIMARY KEY AUTOINCREMENT');
    expect(sql).not.toContain("ENGINE=InnoDB");
  });

  it("emits mysql CREATE TABLE with dialect types and engine", () => {
    const schema = translateModel(TestModel, "mysql");
    const sql = createTableSQL(schema);
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS `tst_user`");
    expect(sql).toContain("`id` INT PRIMARY KEY AUTO_INCREMENT");
    expect(sql).toContain("`tst_name` TEXT");
    expect(sql).toContain("ENGINE=InnoDB");
  });

  it("emits postgres CREATE TABLE with dialect types and identity pk", () => {
    const schema = translateModel(TestModel, "postgres");
    const sql = createTableSQL(schema);
    expect(sql).toContain('CREATE TABLE IF NOT EXISTS "tst_user"');
    expect(sql).toContain(
      '"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'
    );
    expect(sql).toContain('"tst_name" TEXT');
    expect(sql).not.toContain("ENGINE=InnoDB");
    expect(sql).not.toContain("AUTO_INCREMENT");
  });

  it(
    "emits NOT NULL, UNIQUE and maxLength constraints into the DDL",
    () => {
      // src/schema/translation.ts reads @required/@unique/@maxlength via
      // Metadata.validationFor so the constraints reach the DDL.
      const sqlite = createTableSQL(translateModel(TestModel, "sqlite"));
      expect(sqlite).toContain('"tst_name" TEXT NOT NULL');
      expect(sqlite).toContain('"tst_nif" TEXT NOT NULL UNIQUE');
      const mysql = createTableSQL(translateModel(TestModel, "mysql"));
      expect(mysql).toContain("`tst_nif` VARCHAR(9) NOT NULL UNIQUE");
      const postgres = createTableSQL(translateModel(TestModel, "postgres"));
      expect(postgres).toContain('"tst_name" TEXT NOT NULL');
      expect(postgres).toContain('"tst_nif" VARCHAR(9) NOT NULL UNIQUE');
    }
  );

  it("quotes identifiers per dialect for indexes", () => {
    const sqliteSchema = translateModel(TestModel, "sqlite");
    const sqliteSql = createIndexSQL(sqliteSchema);
    expect(sqliteSql.length).toBeGreaterThan(0);
    expect(sqliteSql[0]).toContain("CREATE INDEX IF NOT EXISTS");
    expect(sqliteSql[0]).toContain('ON "tst_user"');

    const mysqlSchema = translateModel(TestModel, "mysql");
    const mysqlSql = createIndexSQL(mysqlSchema);
    expect(mysqlSql.length).toBeGreaterThan(0);
    expect(mysqlSql[0]).toContain("CREATE INDEX ");
    expect(mysqlSql[0]).not.toContain("IF NOT EXISTS");
    expect(mysqlSql[0]).toContain("ON `tst_user`");

    const postgresSchema = translateModel(TestModel, "postgres");
    const postgresSql = createIndexSQL(postgresSchema);
    expect(postgresSql.length).toBeGreaterThan(0);
    expect(postgresSql[0]).toContain("CREATE INDEX IF NOT EXISTS");
    expect(postgresSql[0]).toContain('ON "tst_user"');
  });

  it.each(["sqlite", "postgres"] as const)(
    "join-table DDL uses the generated join table name (%s)",
    (dialect) => {
      // translateModel stores the built Drizzle table in schema.joinTables and
      // generateDDL passes the `{ name }` descriptor to createJoinTableSQL.
      const statements = generateDDL(GenPost, dialect);
      const joined = statements.join("\n");
      expect(joined).toContain('CREATE TABLE IF NOT EXISTS "gen_post"');
      expect(joined).toContain(
        'CREATE TABLE IF NOT EXISTS "gen_post_tags_join"'
      );
      expect(joined).toContain('"source_id" INTEGER NOT NULL');
      expect(joined).toContain('"target_id" INTEGER NOT NULL');
      expect(joined).toContain("PRIMARY KEY");
    }
  );

  it("generates the same statement set shape for both dialects", () => {
    const sqlite = generateDDL(GenTag, "sqlite");
    const mysql = generateDDL(GenTag, "mysql");
    const postgres = generateDDL(GenTag, "postgres");
    expect(sqlite[0]).toContain('"gen_tag"');
    expect(mysql[0]).toContain("`gen_tag`");
    expect(mysql[0]).toContain("ENGINE=InnoDB");
    expect(postgres[0]).toContain('"gen_tag"');
    expect(postgres[0]).toContain("GENERATED BY DEFAULT AS IDENTITY");
    expect(postgres[0]).not.toContain("ENGINE=InnoDB");
  });
});
